#1
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'thid=OIP' | sed -e 's/amp;//g' | awk '$0="http://www.bing.com"$0' >> deleteurl.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1&qft=+filterui%3aimagesize-wallpaper+filterui:photo-photo" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'thid=OIP' | sed -e 's/amp;//g' | awk '$0="http://www.bing.com"$0' >> deleteurl.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1&qft=+filterui%3aimagesize-large+filterui:photo-photo" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'thid=OIP' | sed -e 's/amp;//g' | awk '$0="http://www.bing.com"$0' >> deleteurl.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1&qft=+filterui%3aimagesize-medium+filterui:photo-photo" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'thid=OIP' | sed -e 's/amp;//g' | awk '$0="http://www.bing.com"$0' >> deleteurl.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1&qft=+filterui%3aimagesize-small+filterui:photo-photo" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'thid=OIP' | sed -e 's/amp;//g' | awk '$0="http://www.bing.com"$0' >> deleteurl.txt
cat result/keywordbing.txt > deletekeywordbing.txt
cat result/keyword-how.txt > deletekeyword-how.txt
./start2.sh
cat deletekeywordbing.txt | sort | uniq >> deletekeyword-how.txt
cat deletekeywordbing.txt | sort | uniq | sed -e '/How /d' -e '/how /d' -e '/HOW /d' -e '/can you /d' -e '/what /d' -e '/who /d' -e '/when /d' -e '/why /d' -e '/where /d' -e '/www /d' -e '/www./d' -e '/youtube/d' -e '/youtube /d' -e '/YouTube /d' -e '/adult/d' -e '/sex/d' -e '/fake /d' -e '/2nd /d' -e '/second /d' -e '/ 3d /d' -e '/software/d' -e '/home depot/d' -e '/ app /d' -e '/price/d' -e '/prices/d' -e '/what /d' -e '/ gay /d' -e '/sears /d' -e '/homedepot /d' -e '/walmart /d' -e '/kmart /d' -e '/lowes /d' -e '/ikea /d' -e '/IKEA /d' -e '/houzz /d' -e '/amazon /d' -e '/ebay /d' -e '/hgtv /d' -e '/craigslist /d' -e '/.com /d' | sed -e 's/\"//g' -e 's/\&/and/g' -e 's/-/ /g' -e 's/ 2011//g' -e 's/ 2012//g' -e 's/ 2013//g' -e 's/ 2014//g' -e 's/ 2015//g' -e 's/ 2016//g' -e 's/  //g' | tr -d '\047' > result/keywordbing.txt
cat deletekeyword-how.txt | sort | uniq | grep ' How \| how \| HOW ' > result/keyword-how.txt
#2
cat result/suggest.txt > deletesuggest.txt
cat result/alsosearch.txt > deletealsosearch.txt
cat result/product.txt > deleteproduct.txt
cat result/othersearch.txt > deleteothersearch.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'IRMHRS' | sed -e 's/\/images\/search?q=//g' -e 's/&amp;FORM=IRMHRS//g' -e 's/+/ /g' -e 's/-/ /g' >> deletesuggest.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'IRMHEP' | sed -e 's/\/images\/search?q=//g' -e 's/&amp;FORM=IRMHEP//g' -e 's/+/ /g' -e 's/-/ /g' >> deletealsosearch.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep 'IRMHRE' | sed -e 's/\/images\/search?q=//g' -e 's/&amp;FORM=IRMHRE//g' -e 's/+/ /g' -e 's/-/ /g' >> deleteproduct.txt
wget  -qO- --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" "http://www.bing.com/images/search?q=keyword1" | grep -o 'href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^href=["'"'"']//' -e 's/["'"'"']$//' | grep -e 'IRMHTS' -e 'IRMHIP' | sed -e 's/\/images\/search?q=//g' -e 's/&amp;FORM=IRMHTS//g' -e 's/&amp;FORM=IRMHIP//g' -e 's/+/ /g' -e 's/-/ /g' >> deleteothersearch.txt
cat deletesuggest.txt | sort | uniq > result/suggest
cat deletealsosearch.txt | sort | uniq > result/alsosearch
cat deleteproduct.txt | sort | uniq > result/product
cat deleteothersearch.txt | sort | uniq > result/othersearch
rm -f delete*
